export const LIST_EMPLOYEES_REQUEST = "LIST_EMPLOYEES_REQUEST";
export const LIST_EMPLOYEES_SUCCESS = "LIST_EMPLOYEES_SUCCESS";
export const LIST_EMPLOYEES_FAIL = "LIST_EMPLOYEES_FAIL";

export const EMPLOYEES_DETAILS_REQUEST = "EMPLOYEES_DETAILS_REQUEST";
export const EMPLOYEES_DETAILS_SUCCESS = "EMPLOYEES_DETAILS_SUCCESS";
export const EMPLOYEES_DETAILS_FAIL = "EMPLOYEES_DETAILS_FAIL";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL = "EMPLOYEE_UPDATE_FAIL";
export const EMPLOYEE_UPDATE_RESET = "EMPLOYEE_UPDATE_RESET";

export const CREATE_EMPLOYEE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAIL = "CREATE_EMPLOYEE_FAIL";
export const CREATE_EMPLOYEE_RESET = "CREATE_EMPLOYEE_RESET";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL";
export const DELETE_EMPLOYEE_RESET = "DELETE_EMPLOYEE_RESET";
